name: Build Workflow

run-name: 'Build Workflow -- ${{ github.head_ref || github.ref_name }}'

# Pipeline/Workflow Triggers
on:
    push:
    pull_request:
    workflow_dispatch:

env:
  DATA_PROPERTIES_VERSION: 1.3.5
jobs:
  pr-verification:
    name: Pull Request Validation
    runs-on: ubuntu-24.04
    if: github.event_name == 'pull_request'
    steps:
      - name: Pull Request Version Validation
        uses: ikmdev/maven-pull-request-version-validation-action@v1.0.0
        
  build-job:
    name: Build Job
    runs-on: ubuntu-24.04
    steps:      
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build IKMDEV Code
        uses: ikmdev/maven-clean-install-build-action@v3.3.0
        with:
          branch_name: ${{github.ref_name}}
          mvn_additional_args: -Dtinkar-example-data-properties.version=${{env.DATA_PROPERTIES_VERSION}}
         
