name: SemVer Release Workflow

run-name: "Releasing ${{ github.event.repository.name }} #${{github.run_number}}"

# Trigger workflow manually
on:
  workflow_dispatch:
    inputs:
      release_version:
        type: string
        description: "(Optional) Custom Release Version"
        required: false
      version_type:
        description: 'Development version type to increment'
        required: true
        default: 'minor'
        type: choice
        options:
          - major
          - minor
          - patch

env:
  DATA_PROPERTIES_VERSION: 1.3.9
  BUILD_PROPERTIES_VERSION: 12.55.0
  BRANCH_NAME: ${{ github.ref_name }}
  TRUNK_BRANCH_NAME: ${{ github.event.repository.default_branch }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-24.04
    if: github.repository_owner == 'ikmdev'
    steps:
      - name: Verify Branch
        if: env.BRANCH_NAME != env.TRUNK_BRANCH_NAME
        run: |
          echo "ERROR: Attempting to release from branch ${{ env.BRANCH_NAME }}. Release from ${{ env.TRUNK_BRANCH_NAME }} branch only."
          exit 1

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{secrets.IKMDEVOPS_PAT_TOKEN}}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '23'

      - name: Maven Build Plugin
        shell: bash
        run: |
          ./mvnw clean install\
            --batch-mode \
            -U \
            -e \
            -Dmaven.build.cache.enabled=false \
            -PcodeQuality \
            -f tinkar-example-data-maven-plugin

      - name: Shared Release Action
        uses: ikmdev/maven-semver-release-action@v2.3.0
        with:
          version_type: ${{ github.event.inputs.version_type }}
          github_token: ${{secrets.GITHUB_TOKEN}}
          release_version: ${{ github.event.inputs.release_version }}
          mvn_additional_args: '-Dtinkar-example-data-properties.version=${{ env.DATA_PROPERTIES_VERSION }}'

      - name: Update Dropdown
        run: |
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo LATEST_TAG=$LATEST_TAG
          git config user.name "ikmdevops"
          git config user.email 'devops@ikm.dev'
          git pull -p
          echo "Adding $LATEST_TAG tag to choice dropdown for users attempting to generate data"
          yq -i ".on.workflow_dispatch.inputs.tag_name.options = [\"$LATEST_TAG\"] + .on.workflow_dispatch.inputs.tag_name.options" .github/workflows/generate_data.yaml
          git diff -U1 | grep -E "\-\-\-|\- $LATEST_TAG" -B2 -A1 | grep -v "^--$" > add_tag_choice.patch
          git restore .
          git apply add_tag_choice.patch
          git commit -am"Updated Generate Data Pipeline With $LATEST_TAG"
          git push
