name: Update Environment Workflow

run-name: 'Update Environment Workflow -- DATA_PROPERTIES_VERSION:${{github.event.client_payload.version}}'

# Pipeline/Workflow Triggers
on:
   push:
   workflow_dispatch:
    # repository_dispatch:
    #     types:
    #       - update-repository-dispatch-trigger


env:
  TEST: 1.3.4

jobs:
    update-job:
        name: Update Environment Property
        runs-on: ubuntu-24.04
        # if: github.event_name == 'repository_dispatch' && github.repository_owner == 'ikmdev'
        strategy:
            matrix:
                file-name: [build, post_build, release]
        steps:  
        - name: Checkout Repository
          uses: actions/checkout@v4
          with:
            token: ${{secrets.IKMDEVOPS_PAT_TOKEN}}

        - name: Update Env
          run: |
                git config user.name "ikmdevops"
                git config user.email 'devops@ikm.dev'
                git pull -p

                echo "Updating DATA_PROPERTIES_VERSION environment to $LATEST_VERSION tag in $FILE_NAME"
                yq e -i '.env.DATA_PROPERTIES_VERSION = "${{env.TEST}}"' .github/workflows/$FILE_NAME.yaml
                git diff -U1 -w --ignore-blank-lines | grep -E "\-\-\-|[\+\-]\s+DATA_PROPERTIES_VERSION" -B2 -A1| grep -v "^--$"  > update_$FILE_NAME.patch
                # git restore .
                # git apply update_$FILE_NAME.patch
                # git pull -p;
                # git commit -am"Updated DATA_PROPERTIES_VERSION environment to $LATEST_VERSION in $FILE_NAME"
                # git push
          env:
              LATEST_VERSION:  ${{env.TEST}}
              FILE_NAME: ${{matrix.file-name}}

        - name: Upload ${{matrix.file-name}} File
          uses: actions/upload-artifact@v4
          with:
            name: update_${{matrix.file-name}}.patch
            path: update_${{matrix.file-name}}.patch

    commit-updates:
      name: Commit Updates
      runs-on: ubuntu-24.04
      needs: update-job
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
          with:
            token: ${{secrets.IKMDEVOPS_PAT_TOKEN}}

        - name: Download Files
          uses: actions/download-artifact@v4
          with:
            name: update_build.patch
            # path: patches

        - name: Download Files
          uses: actions/download-artifact@v4
          with:
              name: update_post_build.patch
              # path: patches

        - name: Download Files
          uses: actions/download-artifact@v4
          with:
              name: update_release.patch
              # path: patches

        - name: Commit Changes
          run: |
                git config user.name "ikmdevops"
                git config user.email 'devops@ikm.dev'
                git pull -p

                git apply update_build.patch
                git apply update_post_build.patch
                git apply update_release.patch
                git pull -p;
                git commit -am"Updated DATA_PROPERTIES_VERSION environment to $LATEST_VERSION"
                git push
          
            
          
