name: Update Environment Workflow

run-name: 'Update Environment Workflow -- ${{ github.event.client_payload.origin_repo == 'github_action_test' && "DATA_PROPERTIES_VERSION" || "BUILD_PROPERTIES_VERSION" }}:${{github.event.client_payload.version}}'

# Pipeline/Workflow Triggers
on:
   # push:
   # workflow_dispatch:
    repository_dispatch:
        types:
          - update-repository-dispatch-trigger


env:
  TEST: 1.3.9
  LIST_OF_FILES: "build,post_build,release"

jobs:
    update-job:
        name: Update Environment Property
        runs-on: ubuntu-24.04
        if: github.event_name == 'repository_dispatch' && github.repository_owner == 'ikmdev'
        steps:  
        - name: Checkout Repository
          uses: actions/checkout@v4
          with:
            token: ${{secrets.IKMDEVOPS_PAT_TOKEN}}

        - name: Set Environment Variables Based On Reppo
          id: getEnvironmentVar
          run: |
           if [ "$REPO" == "github_actions_test" ]; then
              echo "ENVIRONMENT=BUILD_PROPERTIES_VERSION" >> $GITHUB_OUTPUT
           else
            echo "ENVIRONMENT=DATA_PROPERTIES_VERSION" >> $GITHUB_OUTPUT
           fi  
          env:
            REPO: ${{github.event.client_payload.origin_repo}}
            

        - name: Update Env
          run: |
                git config user.name "ikmdevops"
                git config user.email 'devops@ikm.dev'
                git pull -p

                # Loop through each file name.
                IFS=',' read -ra files <<< "$FILE_NAMES"

                for file in "${files[@]}"; do
                  echo "Updating $ENVIRONMENT_VAR environment to $LATEST_VERSION tag in $file"
                  yq e -i '.env.$ENVIRONMENT_VAR = "${{github.event.client_payload.version}}"' .github/workflows/$file.yaml
                  git diff -U1 -w --ignore-blank-lines | grep -E "\-\-\-|[\+\-]\s+$ENVIRONMENT_VAR" -B2 -A1| grep -v "^--$"  > update_$file.patch
                  git restore .
                done
                
                git apply *.patch
                git pull -p;
                git commit -am"Updated $ENVIRONMENT_VAR environment to $LATEST_VERSION in $FILE_NAMES"
                git push
          env:
              FILE_NAMES: ${{env.LIST_OF_FILES}}
              LATEST_VERSION: ${{github.event.client_payload.version}}
              ENVIRONMENT_VAR: ${{steps.getEnvironmentVar.outputs.ENVIRONMENT}}
