name: Update Environment Workflow

run-name: 'Update Environment Workflow -- DATA_PROPERTIES_VERSION:${{github.event.client_payload.version}}'

# Pipeline/Workflow Triggers
on:
    repository_dispatch:
        types:
          - update-repository-dispatch-trigger

jobs:
    update-job:
        name: Update Environment Property
        runs-on: ubuntu-24.04
        if: github.event_name == 'repository_dispatch' && github.repository_owner == 'ikmdev'
        strategy:
            matrix:
                file-name: [build, post_build, release]
        steps:  
        - name: Checkout Repository
          uses: actions/checkout@v4
          with:
            token: ${{secrets.IKMDEVOPS_PAT_TOKEN}}

        - name: Update Env
          run: |
                git config user.name "ikmdevops"
                git config user.email 'devops@ikm.dev'
                git pull -p

                echo "Updating DATA_PROPERTIES_VERSION environment to $LATEST_VERSION tag in $FILE_NAME"
                yq e -i '.env.DATA_PROPERTIES_VERSION = ${{github.event.client_payload.version}}' .github/workflows/$FILE_NAME.yaml
                git diff -U1 -w --ignore-blank-lines | grep -E "\-\-\-|[\+\-]\s+DATA_PROPERTIES_VERSION" -B2 -A1| grep -v "^--$"  > update_$FILE_NAME.patch
                git restore .
                git apply update_$FILE_NAME.patch
                git pull -p;
                git commit -am"Updated DATA_PROPERTIES_VERSION environment to $LATEST_VERSION in $FILE_NAME"
                git push
          env:
              LATEST_VERSION:  ${{github.event.client_payload.version}}
              FILE_NAME: ${{matrix.file-name}}
          
