name: Update Environment Workflow

run-name: 'Update Environment Workflow -- DATA_PROPERTIES_VERSION:${{github.event.client_payload.version}}'

# Pipeline/Workflow Triggers
on:
   push:
   workflow_dispatch:
    # repository_dispatch:
    #     types:
    #       - update-repository-dispatch-trigger


env:
  TEST: 1.3.6
  LIST_OF_FILES: "build, post_build, release"

jobs:
    update-job:
        name: Update Environment Property
        runs-on: ubuntu-24.04
        # if: github.event_name == 'repository_dispatch' && github.repository_owner == 'ikmdev'
        steps:  
        - name: Checkout Repository
          uses: actions/checkout@v4
          with:
            token: ${{secrets.IKMDEVOPS_PAT_TOKEN}}

        - name: Update Env
          run: |
                git config user.name "ikmdevops"
                git config user.email 'devops@ikm.dev'
                git pull -p

                # Loop through each file name.
                IFS=',' read -ra files <<< "$FILE_NAMES"

                for file in "${files[@]}"; do
                  echo "Updating DATA_PROPERTIES_VERSION environment to $LATEST_VERSION tag in $file"
                  yq e -i '.env.DATA_PROPERTIES_VERSION = "${{env.TEST}}"' .github/workflows/$file.yaml
                  git diff -U1 -w --ignore-blank-lines | grep -E "\-\-\-|[\+\-]\s+DATA_PROPERTIES_VERSION" -B2 -A1| grep -v "^--$"  > update_$file.patch
                  git restore .
                  git apply update_$file.patch
                done

                git pull -p;
                git commit -am"Updated DATA_PROPERTIES_VERSION environment to $LATEST_VERSION in $FILE_NAMES"
                git push
          env:
              LATEST_VERSION:  ${{env.TEST}}
              FILE_NAMES: ${{env.LIST_OF_FILES}}